# GitHub actions - Create Tesseract installer for Windows

name: Test build for Windows

on:
  push:
#    branches:
#    - 'UB-Mannheim/**'

jobs:
  prepare:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: |
        export
        ls -l

  build32:
    runs-on: [ubuntu-latest]
    needs: [prepare]
    steps:
    - name: Test
      run: |
        export
        ls -l

  build64:
    runs-on: [ubuntu-latest]
    needs: [prepare]
    steps:
    - name: Test
      run: |
        export
        ls -l
